### ISSUE TITLE
dubbo provider没有指定version的时候会失败

### ISSUE THREAD

**Issue by duval1024** [apache/dubbo-python2#3]
Traceback (most recent call last):
  File "/Users/duval/workspace/pycharm/kafkaDemo/Main.py", line 21, in <module>
    result = dubbo_cli.call('listMarket', stockMarket, extraParam)
  File "/usr/local/lib/python2.7/site-packages/dubbo/client.py", line 67, in call
    host = self.__zk_register.get_provider_host(self.__interface)
  File "/usr/local/lib/python2.7/site-packages/dubbo/client.py", line 137, in get_provider_host
    self._get_providers_from_zk(path, interface)
  File "/usr/local/lib/python2.7/site-packages/dubbo/client.py", line 156, in _get_providers_from_zk
    self._register_consumer(providers)
  File "/usr/local/lib/python2.7/site-packages/dubbo/client.py", line 238, in _register_consumer
    'version': provider_fields['version'],
KeyError: 'version'

**Comment by RitterHou** [comment]
provider的version没有默认值，需要手动填写

**Comment by leolinf** [comment]
> provider的version没有默认值，需要手动填写

在哪里手动指定？
